include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore ignore ignore ignore
    avoid_function_literals_in_foreach_calls: ignore
    use_build_context_synchronously: ignore
